server:
  port: 8090
spring:
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest

    retry:
      topic:
        delay: 3s
        multiplier: 3
